address comments

diff --git a/.github/workflows/create-tag.yml b/.github/workflows/create-tag.yml
--- a/.github/workflows/create-tag.yml
+++ b/.github/workflows/create-tag.yml
@@ -83,9 +83,14 @@ jobs:
           SEMVER_RE='^v[0-9]+\.[0-9]+\.[0-9]+$'
           MODULES=( "go.temporal.io/api" "go.temporal.io/sdk" )
           for module in "${MODULES[@]}"; do
-            read -r _ version <<< "$(go list -m "$module")"
+            version=$(go list -f '{{.Version}}' -m "$module")
             if [[ ! "$version" =~ $SEMVER_RE ]]; then
               echo "::error::Using non-tagged version of module $module with version $version"
+              exit 1
+            fi
+            replace=$(go list -f '{{.Replace}}' -m "$module")
+            if [[ "$replace" != "<nil>" ]]; then
+              echo "::error::Module $module is replaced with $replace"
               exit 1
             fi
           done
